import { Platform } from 'react-native';
import RNBlobUtil from 'react-native-blob-util';
import type { jsPDF } from 'jspdf';
import type { PerformanceScanResult, NetworkResourceRow } from './performance-types';
import { formatBytes, formatMs } from './performance-format';

type AutoTableFn = (doc: jsPDF, options: Record<string, unknown>) => void;

type JsPDFWithTable = jsPDF & { lastAutoTable?: { finalY: number } };

function truncate(text: string, max = 80): string {
  if (text.length <= max) return text;
  return `${text.slice(0, max - 1)}…`;
}

function scoreRgb(score: number): [number, number, number] {
  if (score >= 80) return [34, 197, 94];
  if (score >= 60) return [245, 158, 11];
  return [239, 68, 68];
}

function sanitizeFilePart(value: string): string {
  return value.replace(/[^a-zA-Z0-9-_]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
}

function groupResourceTypes(networkTop: NetworkResourceRow[]): Array<{ label: string; value: number }> {
  const totals = new Map<string, number>();
  for (const row of networkTop) {
    const key = row.resourceType || 'other';
    totals.set(key, (totals.get(key) ?? 0) + row.transferSize);
  }
  return [...totals.entries()]
    .map(([label, value]) => ({ label, value }))
    .sort((a, b) => b.value - a.value)
    .slice(0, 8);
}

function drawScoreRing(
  doc: jsPDF,
  cx: number,
  cy: number,
  radius: number,
  score: number,
  rgb: [number, number, number],
  scoreMin?: number,
  scoreMax?: number,
) {
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(2.2);
  doc.circle(cx, cy, radius, 'S');

  const startDeg = -90;
  const sweep = Math.max(0, Math.min(360, (score / 100) * 360));
  doc.setDrawColor(rgb[0], rgb[1], rgb[2]);
  doc.setLineWidth(2.6);
  const steps = Math.max(12, Math.ceil(sweep / 4));
  for (let i = 0; i < steps; i += 1) {
    const a1 = ((startDeg + (sweep * i) / steps) * Math.PI) / 180;
    const a2 = ((startDeg + (sweep * (i + 1)) / steps) * Math.PI) / 180;
    doc.line(
      cx + radius * Math.cos(a1),
      cy + radius * Math.sin(a1),
      cx + radius * Math.cos(a2),
      cy + radius * Math.sin(a2),
    );
  }

  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text(String(Math.round(score)), cx, cy + 1, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text('Score', cx, cy + 7, { align: 'center' });
  if (scoreMin != null && scoreMax != null) {
    doc.setFontSize(7);
    doc.text(`${Math.round(scoreMin)}–${Math.round(scoreMax)}`, cx, cy + 12, { align: 'center' });
  }
}

function drawBarChart(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  height: number,
  title: string,
  items: Array<{ label: string; value: number }>,
  unit: 'ms' | 'bytes',
) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text(title, x, y);

  const chartTop = y + 4;
  const chartLeft = x + 10;
  const chartBottom = chartTop + height - 12;
  const chartHeight = chartBottom - chartTop - 8;
  const chartWidth = width - 14;
  const max = Math.max(...items.map((i) => i.value), 1);
  const slot = chartWidth / Math.max(items.length, 1);
  const barWidth = Math.min(18, slot - 6);

  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.3);
  doc.line(chartLeft, chartTop + 4, chartLeft, chartBottom);
  doc.line(chartLeft, chartBottom, chartLeft + chartWidth, chartBottom);

  items.forEach((item, index) => {
    const barH = Math.max(2, (item.value / max) * chartHeight);
    const bx = chartLeft + index * slot + (slot - barWidth) / 2;
    const by = chartBottom - barH;
    doc.setFillColor(37, 99, 235);
    doc.rect(bx, by, barWidth, barH, 'F');
    doc.setFontSize(7);
    doc.setTextColor(51, 65, 85);
    const valueLabel = unit === 'bytes' ? formatBytes(item.value) : `${Math.round(item.value)} ms`;
    doc.text(valueLabel, bx + barWidth / 2, by - 1.5, { align: 'center' });
    doc.text(item.label, bx + barWidth / 2, chartBottom + 4, { align: 'center' });
  });
}

function addFooters(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated by TWT Locator · Page ${page} of ${pageCount}`, 105, 287, { align: 'center' });
  }
}

function buildPerformancePdf(
  result: PerformanceScanResult,
  jsPDFCtor: typeof import('jspdf').jsPDF,
  autoTable: AutoTableFn,
): jsPDF {
  const doc = new jsPDFCtor({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const margin = 14;
  const pageW = 210;
  const m = result.metrics;
  let y = 18;

  doc.setFillColor(245, 158, 11);
  doc.rect(0, 0, pageW, 22, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('TWT Locator Performance Report', margin, 14);

  y = 30;
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(truncate(m.pageTitle || 'Performance scan', 70), margin, y);

  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const metaLines = [
    `URL: ${truncate(result.url, 95)}`,
    `Final URL: ${truncate(m.finalUrl || result.url, 95)}`,
    `Scanned: ${new Date(result.createdAt || Date.now()).toLocaleString()}`,
    `Viewport: ${result.viewport} · Scan duration: ${formatMs(result.durationMs)}`,
    m.runCount ? `Stable scan: ${m.runCount} passes (median metrics)` : 'Stable scan: 3 passes (median metrics)',
  ];
  for (const line of metaLines) {
    doc.text(line, margin, y);
    y += 4.5;
  }

  drawScoreRing(doc, pageW - margin - 21, 36, 18, result.score, scoreRgb(result.score), m.scoreMin, m.scoreMax);

  y += 4;
  const chartW = pageW - margin * 2;
  const chartH = 52;
  drawBarChart(doc, margin, y, chartW, chartH, 'Core Web Vitals (ms)', [
    { label: 'TTFB', value: m.ttfbMs ?? 0 },
    { label: 'FCP', value: m.fcpMs ?? 0 },
    { label: 'LCP', value: m.lcpMs ?? 0 },
    { label: 'Load', value: m.loadTimeMs ?? 0 },
  ], 'ms');
  y += chartH + 6;

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value', 'Notes']],
    body: [
      ['TTFB', formatMs(m.ttfbMs), 'Time to first byte'],
      ['FCP', formatMs(m.fcpMs), 'First contentful paint'],
      ['LCP', formatMs(m.lcpMs), 'Largest contentful paint'],
      ['DOM complete', formatMs(m.domCompleteMs), 'DOMContentLoaded end'],
      ['Load time', formatMs(m.loadTimeMs), 'Window load event'],
      ['Requests', String(m.requestCount), 'Total network requests'],
      ['Failed requests', String(m.failedRequestCount), 'Non-success responses'],
      ['Transfer size', formatBytes(m.totalTransferBytes), 'Total bytes transferred'],
      ['Third-party bytes', formatBytes(m.thirdPartyBytes), 'Third-party transfer'],
      ['DOM nodes', String(m.domElementCount), 'DOM element count'],
      ['Console errors', String(m.consoleErrorCount), 'Console error count'],
    ],
    styles: { fontSize: 9, cellPadding: 2.5 },
    headStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42] },
    margin: { left: margin, right: margin },
  });

  const docWithTable = doc as JsPDFWithTable;
  y = docWithTable.lastAutoTable?.finalY ?? y + 40;
  y += 8;

  const resourceItems = groupResourceTypes(result.networkTop);
  if (resourceItems.length > 0) {
    if (y > 220) {
      doc.addPage();
      y = margin;
    }
    drawBarChart(doc, margin, y, chartW, chartH, 'Resource types (transfer size)', resourceItems, 'bytes');
    y += chartH + 8;
  }

  if (y > 220) {
    doc.addPage();
    y = margin;
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text(`Findings (${result.findings.length})`, margin, y);
  y += 5;

  if (result.findings.length === 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text('No findings for this run.', margin, y + 4);
  } else {
    autoTable(doc, {
      startY: y,
      head: [['Severity', 'Category', 'Issue', 'Details']],
      body: result.findings.map((f) => [
        f.severity,
        f.category,
        truncate(f.title, 45),
        truncate(f.message, 70),
      ]),
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42] },
      margin: { left: margin, right: margin },
    });
    y = docWithTable.lastAutoTable?.finalY ?? y + 20;
  }

  doc.addPage();
  y = margin;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text(`Network resources (${result.networkTop.length})`, margin, y);
  y += 5;

  if (result.networkTop.length === 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text('No network resources captured.', margin, y + 4);
  } else {
    autoTable(doc, {
      startY: y,
      head: [['URL', 'Type', 'Status', 'Duration', 'Size']],
      body: result.networkTop.map((r) => [
        truncate(r.url, 55),
        r.resourceType,
        String(r.status),
        formatMs(r.durationMs),
        formatBytes(r.transferSize),
      ]),
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42] },
      margin: { left: margin, right: margin },
    });
  }

  addFooters(doc);
  return doc;
}

async function savePdfFile(doc: jsPDF, result: PerformanceScanResult): Promise<string> {
  const created = new Date(result.createdAt || Date.now()).toISOString().slice(0, 10);
  let host = 'report';
  try {
    host = sanitizeFilePart(new URL(result.url).hostname || host);
  } catch {
    host = sanitizeFilePart(result.url) || host;
  }

  const fileName = `performance-report-${host}-${created}.pdf`;
  const dataUri = doc.output('datauristring');
  const base64 = typeof dataUri === 'string' ? dataUri.split(',')[1] ?? '' : '';
  if (!base64) {
    throw new Error('Failed to encode PDF data.');
  }
  const dir =
    Platform.OS === 'android' ? RNBlobUtil.fs.dirs.DownloadDir : RNBlobUtil.fs.dirs.DocumentDir;
  const path = `${dir}/${fileName}`;
  await RNBlobUtil.fs.writeFile(path, base64, 'base64');
  return path;
}

async function openPdfFile(path: string): Promise<void> {
  if (Platform.OS === 'android') {
    await RNBlobUtil.android.actionViewIntent(path, 'application/pdf');
    return;
  }
  await RNBlobUtil.ios.openDocument(path);
}

/** Build PDF with tables + charts, save to device, open in PDF viewer. */
export async function downloadPerformanceReportPdf(result: PerformanceScanResult): Promise<string> {
  const [{ jsPDF }, autoTableModule] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);
  const autoTable = autoTableModule.default as AutoTableFn;
  const doc = buildPerformancePdf(result, jsPDF, autoTable);
  const path = await savePdfFile(doc, result);
  try {
    await openPdfFile(path);
  } catch {
    // File is saved even if no viewer is available (e.g. emulator).
  }
  return path;
}
